apiVersion: v1
kind: Service
metadata:
  name: ap-hl7
  labels:
    run: ap-hl7
spec:
  ports:
  - port: 50051
    protocol: TCP
  type: NodePort
  selector:
    run: ap-hl7
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ap-hl7
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: ap-hl7
    spec:
      containers:
      - name: ap-hl7
        image: sidharder/ap-hl7:v1.2
        ports:
        - containerPort: 50051
